apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-frontend
  template:
    metadata:
      labels:
        app: user-frontend
    spec:
      containers:
        - name: user-frontend
          image: abanobmorkos10/portal_user_frontend
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: docker
            - name: REACT_APP_API_BASE_URL
              value: http://backend:80

---

apiVersion: v1
kind: Service
metadata:
  name: user-frontend
spec:
  type: LoadBalancer
  selector:
    app: user-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
